test
SkillfulDev/online-book-store pull request #13
Opened 2024-04-08 14:47 UTC by SkillfulDev

2024-04-12 15:01 UTC, ReamFOX requested changes
GJ,  but some improvements are needed

2024-04-12 15:01 UTC, ReamFOX commented on src/main/java/ua/chernonog/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER') or hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasAnyRole('ROLE_USER',  'ROLE_ADMIN')")
```
You can use this

2024-04-12 15:01 UTC, ReamFOX commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/CreateBookRequestDto.java
> +    @Size(max = 1000, message = "Description length must be less than 100 characters")
If I saw it correctly, your liquibase script has a 255-character limit in the description. So change it either here or there. I think if a description longer than 255 characters is sent here, the data will simply be lost.

2024-04-12 15:01 UTC, ReamFOX commented on src/main/java/ua/chernonog/onlinebookstore/entity/RoleName.java
> +    ROLE_GUEST
I think ROLE_GUEST redundant, You still have access to authentication endpoints for everyone in the SecurityConfig

2024-04-12 15:01 UTC, ReamFOX commented on src/main/java/ua/chernonog/onlinebookstore/entity/User.java
> +
Yevhen gave me a good idea. You can implement the GrantedAuthority interface in the Role class and reassign the getAuthority() method. to get the String there. And then you can return here just a new HashSet<>.of(roles)

2024-04-12 15:01 UTC, ReamFOX commented on src/main/resources/db/changelog/changes/04-create-roles-table.yaml
> +                  value: ROLE_USER
It would also be better to remove this everywhere
```suggestion
      changes:
        - insert:
            tableName: roles
            columns:
              - column:
                  name: name
                  value: ADMIN
        - insert:
            tableName: roles
            columns:
              - column:
                  name: name
                  value: USER
```

and add ROLE_ in getAuthorities() or getAuthority()

2024-04-13 13:16 UTC, SkillfulDev commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/CreateBookRequestDto.java
> +    @Size(max = 1000, message = "Description length must be less than 100 characters")
you are right

2024-04-13 13:19 UTC, SkillfulDev commented on src/main/java/ua/chernonog/onlinebookstore/entity/RoleName.java
> +    ROLE_GUEST
That I forgot to delete )

2024-04-13 13:38 UTC, SkillfulDev commented on src/main/resources/db/changelog/changes/04-create-roles-table.yaml
> +                  value: ROLE_USER
thanks )

2024-04-15 09:40 UTC, yevheniisynytsia requested changes

2024-04-15 09:40 UTC, yevheniisynytsia commented on src/main/data.txt
> +david.chavez@yahoo.com - +3LgTFrhfS
if this is used in the code - move it to `resources`

2024-04-15 09:40 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/CreateBookRequestDto.java
> +    @Size(max = 255, message = "Description length must be less than 100 characters")
```suggestion
    @Size(max = 255, message = "Description length must be less than 255 characters")
```

2024-04-15 09:40 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/service/impl/AuthenticationServiceImpl.java
> +                RuntimeException::new);
use another exception and specify the exception message

2024-04-15 09:40 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: decimal(38,2)
you must not change already applied migration files. Please read about checksum

2024-04-15 09:40 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: decimal(38,2)
I also recommend looking into liquibase `computedValue` and trying to use it. It is a good practice

2024-04-15 10:32 UTC, SkillfulDev commented on src/main/data.txt
> +david.chavez@yahoo.com - +3LgTFrhfS
It wasn’t supposed to get into git

2024-04-15 10:49 UTC, SkillfulDev commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: decimal(38,2)
> you must not change already applied migration files. Please read about checksum

in the following changes I will do so (I had many changes and I decided to redo initially )

2024-04-15 10:50 UTC, SkillfulDev commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: decimal(38,2)
> I also recommend looking into liquibase `computedValue` and trying to use it. It is a good practice

I use this in 06-insert-values-into-users.yaml

2024-04-15 11:30 UTC, yevheniisynytsia approved these changes

2024-04-15 11:30 UTC, yevheniisynytsia commented on data.txt
> +david.chavez@yahoo.com - +3LgTFrhfS
please remove before merge

2024-04-15 11:55 UTC, merged