Adding category model
SkillfulDev/online-book-store pull request #15
Opened 2024-04-16 09:03 UTC by SkillfulDev

2024-04-22 10:07 UTC, yevheniisynytsia requested changes
Great job! Left some comments

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/config/JwtAuthenticationExceptionHandler.java
> +    private final ObjectMapper mapper = new ObjectMapper();
let's add a bean of object mapper and configure it somewhere in a configuration class. It will be useful in future

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/config/JwtAuthenticationExceptionHandler.java
> +    protected void doFilterInternal(
could you please tell me why it is needed?

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/controller/CategoryController.java
> +        return categoryService.getBookByCategory(id,pageable);
```suggestion
        return categoryService.getBookByCategory(id, pageable);
```

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/category/CreateCategoryDto.java
> +    @NotBlank(message = "Name can't be empty")
please add size constraint

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/exception/dto/ErrorDto.java
> +public record ErrorDto(
```suggestion
public record ErrorRespone(
```
TBH I like it more, but up to you

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/mapper/BookMapper.java
> +    }
From task description:

Modify the BookMapper class to have such methods:
BookDto toDto(Book book);
Book toEntity(CreateBookRequestDto bookDto);
BookDtoWithoutCategoryIds toDtoWithoutCategories(Book book); (HINT: BookDtoWithoutCategoryIds class could be used as a response class for @GetMapping("/{id}/books") endpoint)
@AfterMapping default void setCategoryIds(@MappingTarget BookDto bookDto, Book book)

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/service/impl/BookServiceImpl.java
> +    public List<BookDtoWithoutCategoryIds> getBookByCategory(Category category, Pageable pageable) {
you don't need `Category` here, you can pass its id

2024-04-22 10:07 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/service/impl/CategoryServiceImpl.java
> +        return bookService.getBookByCategory(categoryFromBD, pageable);
pass only ID, no need to get category object

2024-04-23 13:31 UTC, SkillfulDev commented on src/main/java/ua/chernonog/onlinebookstore/config/JwtAuthenticationExceptionHandler.java
> +    protected void doFilterInternal(
For handling an exception at the filter stage, as we cannot throw out our custom exceptions in Global Exceptions when we have a non-essential JWT Token

2024-04-23 13:33 UTC, SkillfulDev commented on src/main/java/ua/chernonog/onlinebookstore/exception/dto/ErrorDto.java
> +public record ErrorDto(
Agree

2024-04-23 15:01 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-04-23 15:01 UTC, andrii-hoienko commented on src/main/java/ua/chernonog/onlinebookstore/config/UtilConfig.java
> +public class UtilConfig {
```suggestion
public class JacksonConfig {
```

2024-04-23 15:01 UTC, andrii-hoienko commented on src/main/java/ua/chernonog/onlinebookstore/config/JwtAuthenticationExceptionHandler.java
> +public class JwtAuthenticationExceptionHandler extends OncePerRequestFilter {
I believe it should be in exception package

2024-04-23 15:01 UTC, andrii-hoienko commented on src/main/java/ua/chernonog/onlinebookstore/controller/CategoryController.java
> +
```suggestion
```

2024-04-23 15:01 UTC, andrii-hoienko commented on src/main/java/ua/chernonog/onlinebookstore/exception/JwtTokenValidException.java
> +    public JwtTokenValidException(String msg, Throwable cause) {
```suggestion
    public JwtTokenValidException(String meassage, Throwable cause) {
```

2024-04-24 13:56 UTC, andrii-hoienko approved these changes
Gj!

2024-04-25 11:04 UTC, merged