Feature/book store impl gl exception
SkillfulDev/online-book-store pull request #4
Opened 2024-04-02 12:50 UTC by SkillfulDev

2024-04-04 13:19 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2024-04-04 13:19 UTC, andrii-hoienko commented on src/main/java/ua/chernonog/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        return getStandartTemplateOfResponseEntity(e);
Is this case getStandartTemplateOfResponseEntity method will return HttpStatus.CONFLICT, but I believe HttpStatus.NOT_FOUND should be returned, please check other methods as well and choose appropriate status code

2024-04-04 13:19 UTC, andrii-hoienko commented on src/main/java/ua/chernonog/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +                body, HttpStatus.CONFLICT);
Bad request status not matches with conflict status, please be consistent or remove body.put(STATUS, HttpStatus.BAD_REQUEST);

2024-04-04 13:19 UTC, andrii-hoienko commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/CreateBookRequestDto.java
> +    @Pattern(regexp = "^(?:\\d{9}[\\dX]|97[89]\\d{10})$", message = "Invalid ISBN format")
I believe that there are already exists some @ISDN validation annotation, please check it out

2024-04-08 08:21 UTC, yevheniisynytsia requested changes

2024-04-08 08:21 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/CreateBookRequestDto.java
> +    @NotEmpty(message = "Title cannot be empty")
do you want to accept `" "` values?
I think `@NotBlank` is better 
https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2024-04-08 08:21 UTC, yevheniisynytsia commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/CreateBookRequestDto.java
> +    @NotEmpty(message = "ISBN cannot be empty")
I think `@NotNull` is enough here, not sure how `@ISBN` works in details though

2024-04-08 08:34 UTC, SkillfulDev commented on src/main/java/ua/chernonog/onlinebookstore/dto/request/CreateBookRequestDto.java
> +    @NotEmpty(message = "ISBN cannot be empty")
Using both annotations together ensures that the field is checked for void first and then against a specific format. They do not contradict each other, but complement the validation process, ensuring that the ISBN field is not empty, and correctly formatted.

2024-04-08 09:40 UTC, yevheniisynytsia approved these changes
Well done!

2024-04-08 10:00 UTC, closed without merging